# Generated by Django 2.2.5 on 2019-11-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img500x600', models.ImageField(height_field=600, upload_to='images/', width_field=500)),
                ('img300x400', models.ImageField(height_field=400, upload_to='images/', width_field=300)),
                ('img100x100', models.ImageField(height_field=100, upload_to='images/', width_field=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
