# Generated by Django 2.2.5 on 2019-11-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
    ]
