# Generated by Django 2.2.5 on 2019-11-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
