# Generated by Django 2.2.5 on 2019-11-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191123_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='img100x100',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='img300x400',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='img500x600',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product'),
        ),
    ]
