# Generated by Django 2.2.5 on 2019-11-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_featured'),
        ('shop', '0002_order'),
    ]

    operations = [
    ]
