# Generated by Django 2.2.5 on 2019-11-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_merge_20191123_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
