# Generated by Django 3.0.1 on 2020-01-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20191227_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food & Drink'), (2, 'Clothing'), (3, 'Technology'), (4, 'Miscellaneous')], default=4),
        ),
    ]
